### PR TITLE
API-189: Fix bug with nunit3 - "agents" is not a local variable

### PR DESCRIPTION
**Pull request by kieranlynam**
http://youtrack.zopian.ad.zopa.com/issue/API-189

Fix bug introduced in https://github.com/zopaUK/bozo-scripts/pull/72#discussion_r96280294

🔍 @lukesmith @xiaoqingzhang

### CODE REVIEW

**Comment by xiaoqingzhang** [comment]
👍

File: lib/bozo/test_runners/nunit3.rb [hunk 1]
```diff
@@ -61,7 +61,7 @@ def runner_args
         args << '--x86'
       end
 
-      unless !agents || agents.empty?
+      unless !@agents || @agents.empty?
```
Comment (kieranlynam) [inline lib/bozo/test_runners/nunit3.rb]: @lukesmith [didn't work](http://bob.zopa.local:8080/job/kashmir-feature-ci/144/console) :(

```
Running tests
  Running tests with Bozo::TestRunners::Nunit3
  Found runner at d:/jenkins/workspace/kashmir-feature-ci/packages/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe
#<NoMethodError: undefined method `empty?' for 1:Fixnum>
```
